mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as userViews
from . import views as mainViews
from django.contrib.auth import views as authViews
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('purchase/', include('purchase.urls'), name='purchase'),
    path('reg/', userViews.register, name='reg'),
    path('profile/', userViews.profile, name='profile'),
    path('login/', authViews.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('exit/', authViews.LogoutView.as_view(template_name='users/exit.html'), name='exit'),
    path('', mainViews.main_page, name='main'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls)), ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

purchase/urls.py
from django.urls import path
from . import views

app_name = 'purchase'
urlpatterns = [
    path('', views.PurchaseListView.as_view(), name='index'),
    # ex: /purchase/5/
    path('<int:pk>/', views.PurchaseDetailView.as_view(), name='detail'),
    path('<int:pk>/files/', views.PurchaseFiles.as_view(), name='files'),
    path('<int:pk>/update/', views.PurchaseUpdateView.as_view(), name='purchase-update'),
    path('<int:pk>/delete/', views.PurchaseDeleteView.as_view(), name='purchase-delete'),
    path('add/', views.PurchaseCreateView.as_view(), name='purchase-add'),
    path('my_purchases/', views.MyPurchasesListView.as_view(), name='my-purchases'),
    path('my_approves/', views.MyApprovesListView.as_view(), name='my-approves'),
]

purchase/models.py
import os
from pprint import pprint

from django.conf import settings
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from mysite.settings import MEDIA_ROOT
from users.models import ProfileTree
from django.contrib.auth.models import User


# Create your models here.


class PurchaseRequest(models.Model):

    def purchase_file_path(self, filename):
        return f'purchase_files/{self.pk}/{filename}'

    class StatusChoices(models.TextChoices):
        CREATED = '0', _('Создана')
        TO_CONFIRM = '1', _('На согласовании')
        TO_APPROVE = '2', _('На утверждении')
        APPROVED = '3', _('Утверждена')
        MODIFY = '4', _('Отклонена')
        FIXED = '5', _('На согласовании после доработки')

    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, verbose_name='Наименование объекта закупки')
    goods = models.TextField(verbose_name='Спецификация товаров, работ, услуг')
    supplier = models.CharField(max_length=200, verbose_name='Наименование поставщика')
    offer = models.FloatField(verbose_name='Ценовое предложение поставщика')
    apply_date = models.DateTimeField(auto_now_add=True)
    last_action_date = models.DateTimeField(default=timezone.now)
    status = models.CharField(
        max_length=50,
        choices=StatusChoices.choices,
        default=StatusChoices.CREATED
    )

    # files = models.FileField(verbose_name='Файлы', null=True, blank=True, upload_to=purchase_file_path)

    def __str__(self):
        return self.title

    #  При создании новой записи в БД возвращает url новой записи (для редиректа на страницу с новой закупкой)
    def get_absolute_url(self):
        return reverse('purchase:detail', kwargs={'pk': self.pk})

    def is_approved(self):
        if self.status == self.StatusChoices.TO_APPROVE:
            return True
        approves = PurchaseApprove.objects.filter(purchase=self.pk)
        for approve in approves:
            if approve.approver_choice == '' or approve.approver_choice == PurchaseApprove.ApproveChoices.values[1]:
                return False
        if self.status == self.StatusChoices.TO_CONFIRM or self.status == self.StatusChoices.FIXED:
            self.status = self.StatusChoices.TO_APPROVE
            self.save()
        return True

    def save(self, *args, **kwargs):
        # Note that change is False at the very first time
        update_fields = []
        if kwargs:
            for key, value in kwargs['form'].cleaned_data.items():
                # True if something changed in model
                if value != kwargs['form'].initial[key]:
                    update_fields.append(key)
            super().save(update_fields=update_fields)
        else:
            super().save()


class PurchaseRequestFiles(models.Model):

    def get_filename(self):
        s = self.file.name.split('/')
        return s[-1]

    purchase = models.ForeignKey(PurchaseRequest, db_index=True, on_delete=models.CASCADE)
    file = models.FileField(upload_to='purchase_files/%Y/%m/%d/', verbose_name='Файлы')


class PurchaseApprove(models.Model):
    ApproveChoices = models.TextChoices('Решение по закупке', 'Согласована Отклонена')

    purchase = models.ForeignKey(PurchaseRequest, on_delete=models.CASCADE)
    approver = models.ForeignKey(ProfileTree, on_delete=models.PROTECT)
    approver_choice = models.CharField(blank=True, choices=ApproveChoices.choices, max_length=20)

purchase/forms.py
from crispy_forms.helper import FormHelper
from django import forms
from django.forms import widgets

from purchase.models import PurchaseRequestFiles


class ApproveForm(forms.Form):
    comment = forms.CharField(required=False, label='Комментарий',
                              widget=forms.Textarea(attrs={
                                "rows": 4,
                                "cols": 50,
                                "class": "form-control"
                                }))


class PurchaseCreateForm(forms.Form):
    files = forms.FileField(label='Прикрепить файлы', widget=widgets.FileInput(attrs={'multiple': True}))

    def __init__(self, *args, **kwargs):
        if 'request' in kwargs:
            self.request = kwargs.pop('request')
        super(PurchaseCreateForm, self).__init__(*args, **kwargs)
        #self.helper = FormHelper()

    def clean_files(self):
        files = [f for f in self.request.FILES.getlist('files')]
        return files

    def save_for(self, purchase):
        for file in self.clean_files():
            PurchaseRequestFiles(purchase=purchase, file=file).save()

purchase/views.py
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic.edit import FormMixin
from django.contrib import messages

from users.models import ProfileTree
from .forms import ApproveForm, PurchaseCreateForm
from .models import PurchaseRequest, PurchaseApprove, PurchaseRequestFiles
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


# Create your views here.


class PurchaseListView(LoginRequiredMixin, ListView):
    model = PurchaseRequest
    template_name = 'purchase/index.html'
    context_object_name = 'purchase_list'
    ordering = ['-apply_date']

    def get_queryset(self):
        return PurchaseRequest.objects.exclude(status=PurchaseRequest.StatusChoices.CREATED).order_by('-apply_date').select_related('author')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Закупки'
        return context


class MyPurchasesListView(LoginRequiredMixin, ListView):
    model = PurchaseRequest
    template_name = 'purchase/my_purchases.html'
    context_object_name = 'purchase_list'
    ordering = ['-apply_date']

    def get_queryset(self):
        user = self.request.user  # Получаю объект текущего пользователя
        return PurchaseRequest.objects.filter(author=user).order_by('-apply_date').select_related('author')

    def get_context_data(self, **kwargs):
        context = super(MyPurchasesListView, self).get_context_data(**kwargs)
        context['title'] = 'Мои заявки на закупку'
        return context


class MyApprovesListView(LoginRequiredMixin, ListView):
    model = PurchaseRequest
    template_name = 'purchase/my_approves.html'
    context_object_name = 'purchase_list'
    ordering = ['-apply_date']

    def get_queryset(self):
        user = ProfileTree.objects.get(user=self.request.user)  # Получаю объект текущего пользователя
        if self.request.user.has_perm('purchase.can_approve'):
            req = PurchaseRequest.objects.filter(status=PurchaseRequest.StatusChoices.TO_APPROVE)
        else:
            purchase_list = PurchaseApprove.objects.select_related('purchase').filter(approver=user)
            req = PurchaseRequest.objects.filter(Q(purchaseapprove__in=purchase_list),
                                                 Q(status=PurchaseRequest.StatusChoices.TO_CONFIRM) |
                                                 Q(status=PurchaseRequest.StatusChoices.FIXED)
                                                 ).select_related('author')
        return req

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Согласование заявок'
        return context


class PurchaseDetailView(FormMixin, LoginRequiredMixin, DetailView):
    model = PurchaseRequest
    template_name = 'purchase/details.html'
    form_class = ApproveForm

    # def get_queryset(self):
    #     return PurchaseRequest.objects.filter(pk=self.kwargs['pk']).select_related('author')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        purchase = self.object
        context['title'] = purchase.title

        purchase_approves = PurchaseApprove.objects.filter(purchase=purchase).select_related('purchase', 'approver')
        context['purchase_approves'] = dict((key, key.approver.user) for key in purchase_approves)

        # Если текущий пользователь обладает разрешением на утверждение заявки
        # и заявка находится в статусе "На утверждении"
        if self.request.user.has_perm('purchase.can_approve') and purchase.status == PurchaseRequest.StatusChoices.TO_APPROVE:
            context['can_approve'] = True

        return context

    """Обработка формы в POST запросе"""

    def form_valid(self, form):
        purchase = PurchaseRequest.objects.get(pk=self.kwargs['pk'])
        if purchase.status == PurchaseRequest.StatusChoices.TO_CONFIRM or \
                purchase.status == PurchaseRequest.StatusChoices.FIXED:
            if 'approve-btn' in self.request.POST:
                user = self.request.user
                approve = PurchaseApprove.objects.get(purchase=purchase, approver__user=user)
                if approve.approver_choice == '':
                    approve.approver_choice = PurchaseApprove.ApproveChoices.values[0]
                    approve.save()
                    messages.add_message(self.request, messages.SUCCESS, f'Закупка успешно согласована')
                    purchase.is_approved()
                else:
                    messages.add_message(self.request, messages.WARNING, f'Вы уже принимали решение по данной закупке')
            elif 'reject-btn' in self.request.POST:
                user = self.request.user
                purchase = PurchaseRequest.objects.filter(pk=self.kwargs['pk']).first()
                approve_list = PurchaseApprove.objects.filter(purchase=purchase)
                approve = approve_list.get(approver__user=user)
                if approve.approver_choice == '':
                    for current in approve_list:
                        if current == approve:
                            current.approver_choice = PurchaseApprove.ApproveChoices.values[1]
                            current.save()
                            messages.add_message(self.request, messages.ERROR, f'Закупка отклонена', extra_tags='danger')
                        else:
                            current.approver_choice = ''
                            current.save()
                    purchase.status = PurchaseRequest.StatusChoices.MODIFY
                    purchase.save()
                else:
                    messages.add_message(self.request, messages.WARNING, f'Вы уже принимали решение по данной закупке')
        elif purchase.status == PurchaseRequest.StatusChoices.TO_APPROVE:
            if 'approve-btn' in self.request.POST:
                purchase.status = PurchaseRequest.StatusChoices.APPROVED
                purchase.save()
                messages.add_message(self.request, messages.SUCCESS, f'Закупка согласована')

            elif 'reject-btn' in self.request.POST:
                purchase.status = PurchaseRequest.StatusChoices.MODIFY
                purchase.save()
                messages.add_message(self.request, messages.ERROR, f'Закупка отклонена', extra_tags='danger')
        else:
            messages.add_message(self.request, messages.ERROR,
                                 f'Невозможно выполнить действие, так как закупка находится '
                                 f'в статусе {self.get_object().get_status_display()}', extra_tags='danger')

        # TODO: Реализовать сохранение комментариев к закупке
        # print(form.cleaned_data['comment'])
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        # self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_success_url(self):
        return reverse("purchase:detail", kwargs={'pk': self.kwargs['pk']})


class PurchaseCreateView(LoginRequiredMixin, CreateView):
    model = PurchaseRequest
    fields = ['title', 'goods', 'supplier', 'offer']
    form_files_class = PurchaseCreateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form_files = self.form_files_class()
        context['form_files'] = form_files
        return context

    def post(self, request, *args, **kwargs):
        self.object = []
        formclass = self.get_form_class()
        templatename = self.get_template_names()
        form = formclass(request.POST)
        print(request.FILES)
        form_files = self.form_files_class(request.POST, request.FILES, request=self.request)
        if form.is_valid() and form_files.is_valid():
            form.instance.author = self.request.user
            if 'confirm-btn' in self.request.POST:
                form.instance.status = PurchaseRequest.StatusChoices.TO_CONFIRM
            purchase = form.save()
            form_files.save_for(purchase)
            return HttpResponseRedirect('/')
        return render(request, templatename, {'form': form, 'form_files': form_files})

    # def form_valid(self, form):
    #     print('FORM VALID')
    #     form.instance.author = self.request.user
    #     if 'confirm-btn' in self.request.POST:
    #         form.instance.status = PurchaseRequest.StatusChoices.TO_CONFIRM
    #     return super().form_valid(form)


class PurchaseUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = PurchaseRequest
    fields = ['title', 'goods', 'supplier', 'offer']

    def form_valid(self, form):
        purchase = self.object
        if 'confirm-btn' in self.request.POST:
            if purchase.status == PurchaseRequest.StatusChoices.MODIFY:
                form.instance.status = PurchaseRequest.StatusChoices.FIXED
                approve_list = PurchaseApprove.objects.filter(purchase=purchase).select_related('approver')
                for current in approve_list:
                    current.approver_choice = ''
                    current.save()
            elif purchase.status == PurchaseRequest.StatusChoices.CREATED:
                form.instance.status = PurchaseRequest.StatusChoices.TO_CONFIRM
        return super().form_valid(form)

    def test_func(self):
        purchase = self.get_object()
        if self.request.user == purchase.author:
            return True
        return False


class PurchaseDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = PurchaseRequest
    success_url = '/purchase/'

    def test_func(self):

purchase/templates/purchase/details.html
{% extends 'purchase/main_purchases.html' %}
{% load crispy_forms_tags %}
{% block purchase_section %}

<div class="col-md-9 ml-0 border mb-2">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a class="nav-link active" href="{% url 'purchase:detail' object.id %}">Общая информация</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'purchase:files' object.id %}">Прикрепленные файлы</a>
      </li>
    </ul>
    <div class="row">
        <div class="col text-right">
            Утверждаю <br>
            Директор ОБУ "Ледовая Арена "Трактор"<br>
            Телих Д.С.
        </div>
    </div>
    <div class="row">
        <div class="col text-center ">
            <h4> Заявка на осуществление закупки </h4>
        </div>
    </div>
    <div class="row">
        <div class="col text-center py-3">
            В связи с ___________ прошу разрешить закупку следующих товаров, работ (услуг)
        </div>
    </div>
    <div class="row">
        <div class="col border py-3">
            Наименование закупки
        </div>
        <div class="col border py-3">
            Описание товаров, работ, услуг:
        </div>
        <div class="col border py-3">
            Ориентировочная стоимость, руб:
        </div>
    </div>
    <div class="row">
        <div class="col border py-3">
            {{object.title}}
        </div>
        <div class="col border py-3">
            {{object.goods}}
        </div>
        <div class="col border text-right py-3">
            {{object.offer}}
        </div>
    </div>
    <div class="row">
        <div class="col border py-3">
            Вышеуказанные товары, работы (услуги), по результатам проведенного мониторинга цен, прошу приобрести у
            {{object.supplier}}
            по цене, не превышающей среднего уровня цен.
        </div>
    </div>
    <div class="row">
        <div class="col border py-2">
            Инициатор закупки <br>
            (Руководитель структурного подразделения)
        </div>
        <div class="col border text-right py-2">
            {{object.author}}
        </div>
    </div>
    <div class="row">
        <div class="col border text-right py-2">
            {{ object.last_action_date }}
        </div>
    </div>

    <div class="row">
        <div class="col">
            <h4>Этапы согласования</h4>
        </div>
    </div>

    {% for approve in purchase_approves%}
    <div class="row">
        <div class="col border">
            {{approve.approver.position}}
        </div>
        {% if approve.approver_choice %}
        <div class="col text-center border">
            {{ approve.approver_choice}}
        </div>
        {% else %}
        <div class="col text-center border">
            На согласовании
        </div>
        {% endif %}
        <div class="col text-right border">
            {{approve.approver.first_name}} {{ approve.approver.last_name }}
        </div>
    </div>
    {% endfor %}

    {% if object.author == user %}
    {% if object.status == '0' or object.status == '4'%}
    <hr>
    <div class="text-right">
        <a href="{% url 'purchase:purchase-delete' object.id %}" class="btn btn-outline-secondary"> Удалить заявку</a>
        <a href="{% url 'purchase:purchase-update' object.id %}" class="btn btn-outline-secondary"> Изменить заявку</a>
    </div>
    {% endif %}
    {% endif %}

</div>
{% for approve, approver_user in purchase_approves.items%}
{% if approver_user == user %}
<div class="form-group col-md-9 offset-2">
    <form class="form-inline col-md-7" action="{% url 'purchase:detail' object.id %}" method="POST">
        {% csrf_token %}
        {{ form.as_table }}

        <p>
            <button type="submit" name="approve-btn" class="btn btn-outline-success mt-4 mr-4"> Согласовать</button>
        </p>
        <p>
            <button type="submit" name="reject-btn" class="btn btn-outline-danger mt-4"> Отклонить</button>
        </p>

    </form>
</div>
{% endif %}
{% endfor %}

{% if can_approve %}
<div class="form-group col-md-9 offset-2">
    <form class="form-inline col-md-7" action="{% url 'purchase:detail' object.id %}" method="POST">
        {% csrf_token %}
        {{ form.as_table }}

        <p>
            <button type="submit" name="approve-btn" class="btn btn-outline-success mt-4 mr-4"> Согласовать</button>
        </p>
        <p>
            <button type="submit" name="reject-btn" class="btn btn-outline-danger mt-4"> Отклонить</button>
        </p>

    </form>
</div>
{% endif %}
{% endblock purchase_section %}

purchase/templates/purchase/index.html
{% extends 'purchase/main_purchases.html' %}
{% block purchase_section %}
    {% if purchase_list %}
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4"><div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
            <h1 class="h2">{{ title }}</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
                <a href="{% url 'purchase:purchase-add' %}" class="btn btn-sm btn-outline-secondary">Создать заявку на закупку</a>
              </div>
              <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-calendar"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg>
                This week
              </button>
            </div>
          </div>
          <div class="table-responsive">
            <table class="table table-striped table-sm">
                <thead class="thead-dark">
                        <tr>
                          <th scope="col">#</th>
                          <th scope="col">Закупка</th>
                          <th scope="col">Поставщик</th>
                          <th scope="col">Стоимость</th>
                          <th scope="col">Исполнитель</th>
                          <th scope="col">Дата</th>
                          <th scope="col">Статус</th>
                        </tr>
                      </thead>
                      <tbody>
                       {% for purchase in purchase_list %}
                        <tr>
                          <th scope="row">{{ forloop.counter }}</th>
                          <td><a href="{% url 'purchase:detail' purchase.id %}">{{ purchase.title }}</a></td>
                          <td>{{ purchase.supplier }}</td>
                          <td>{{ purchase.offer }}</td>
                          <td>{{ purchase.author }}</td>
                          <td>{{ purchase.apply_date|date:"d.m.Y"}}</td>
                          <td>{{ purchase.get_status_display}}</td>
                        </tr>
                      {% endfor %}
                      </tbody>
            </table>
          </div>
        </main>

    {% else %}
      <p>No polls are available.</p>
    {% endif %}

{% endblock purchase_section %}

purchase/templates/purchase/main_page.html
{% extends 'purchase/main.html' %}
{% block main_section %}
    <h2>Главная страница сайта!</h2>

{% endblock main_section %}

purchase/templates/purchase/main_purchases.html
{% extends 'purchase/main.html' %}

{% block main_section %}
 <div class="row">
    <nav class="col-md-2 d-none d-md-block bg-light sidebar">
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'purchase:index' %}">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
              Все закупки
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'purchase:my-purchases' %}">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-cart"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg>
              Мои заявки на закупку <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'purchase:my-approves' %}">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg>
              Согласование заявок
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
              Задачи
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bar-chart-2"><line x1="18" y1="20" x2="18" y2="10"></line><line x1="12" y1="20" x2="12" y2="4"></line><line x1="6" y1="20" x2="6" y2="14"></line></svg>
              Отчеты
            </a>
          </li>
        </ul>
      </div>
    </nav>
    {% block purchase_section %}
    {% endblock purchase_section %}
 </div>
{% endblock main_section %}

purchase/templates/purchase/purchase_files.html
{% extends 'purchase/main_purchases.html' %}
{% block purchase_section %}

<div class="col-md-9 ml-0 border mb-2">
        <ul class="nav nav-tabs">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'purchase:detail' purchase%}">Общая информация</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'purchase:files' purchase%}">Прикрепленные файлы </a>
          </li>
        </ul>
    {% for file in object_list%}
    <div class="col-md-9 mt-3">
        <div class="row">
        <div class="col-md-auto">
            {{ file.get_filename }}
        </div>
        <div class="col-3 text-right">
            <a href="{{file.file.url}}" target="_blank">Просмотреть</a>
            <a href="{{file.file.url}}" download>Скачать</a>
        </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock purchase_section %}

purchase/templates/purchase/purchaserequest_confirm_delete.html
{% extends 'purchase/main_purchases.html' %}
{% block purchase_section %}
    <div class="form-section">
        <h2>Удалить заявку: "{{ object.title }}"?</h2>
        <form method="POST">
            {% csrf_token %}
        <button type="submit" class="btn btn-outline-danger">Удалить</button>
        <a href="{% url 'purchase:detail' object.id %}">Отмена</a>
        </form>
    </div>
{% endblock purchase_section %}